In [7]:
# Import packages
import sys
import os

sys.path[0] = os.path.dirname(os.getcwd())

from tools import execute_statement

import pandas as pd
import numpy as np
pd.set_option("display.max_columns", None)

In [4]:
# Extract NFL QB data from local postgres database
df = execute_statement("select * from archive_data.weekly_qb")

In [5]:
df.head()

player_name position recent_team  season  week  comp_pct  passing_yards  \
0       J.Burrow       QB         CIN    2021    12       0.0          190.0   
1      P.Mahomes       QB          KC    2022     6       0.0          338.0   
2       K.Murray       QB         ARI    2022     8       0.0          326.0   
3  T.Bridgewater       QB         CAR    2020     5       0.0          313.0   
4       J.Flacco       QB         BAL    2018     3       0.0          277.0   

   passing_tds  interceptions  sacks  sack_yards  passing_air_yards  \
0            1            1.0    2.0        18.0              176.0   
1            2            2.0    3.0        19.0              220.0   
2            3            2.0    4.0        29.0              288.0   
3            2            0.0    0.0         0.0              218.0   
4            1            0.0    2.0        12.0              365.0   

   passing_yards_after_catch  passing_first_downs  passing_epa    dakota  \
0                       92.0                 11.0     2.284419  0.205053   
1                      199.0                 16.0     4.380725  0.106046   
2                      179.0                 17.0    -1.212212  0.037566   
3                      178.0                 18.0    16.785227  0.235966   
4                       97.0                 13.0     6.875180  0.111369   

       pacr  avg_time_to_throw  avg_completed_air_yards  \
0  1.079546           2.682792                 4.989500   
1  1.536364           3.103200                 4.835200   
2  1.131944           2.500488                 4.715161   
3  1.435780           2.527750                 4.610741   
4  0.758904           2.517769                 6.850400   

   avg_intended_air_yards  avg_air_yards_differential  aggressiveness  \
0                7.504348                   -2.514848       12.500000   
1                5.775714                   -0.940514       12.500000   
2                6.601860                   -1.886699       13.636364   
3                6.113235                   -1.502495        8.333333   
4                9.219231                   -2.368831       27.500000   

   max_completed_air_distance  avg_air_yards_to_sticks  passer_rating  \
0                   50.249253                -2.626087      96.180556   
1                   35.337781                -3.910000      85.208333   
2                   37.962057                -2.746977      95.454545   
3                   37.004088                -1.857353     119.328704   
4                   44.137033                 1.116667      91.354167   

   completion_percentage_above_expectation  avg_air_distance  carries  \
0                                16.698358         21.392319        1   
1                                 0.560848         19.420351        4   
2                                 2.397371         20.311839        6   
3                                 8.392194         18.779622        3   
4                                 6.892144         22.457097        4   

   rushing_yards  rushing_tds  rushing_fumbles  rushing_fumbles_lost  \
0            8.0            1              0.0                   0.0   
1           21.0            0              0.0                   0.0   
2           36.0            0              1.0                   0.0   
3            3.0            0              0.0                   0.0   
4            2.0            0              0.0                   0.0   

   rushing_first_downs  rushing_epa  offense_snaps  offense_pct  total_usage  \
0                  1.0     1.873802           58.0         0.85           25   
1                  2.0     2.303693           67.0         1.00           44   
2                  0.0    -0.650172           78.0         1.00           50   
3                  0.0    -2.186499           66.0         1.00           39   
4                  1.0     0.001535           72.0         1.00           44   

       roof    surface weather_hazards  temp  humidity

In [8]:
# Create test array to use with matrix
week_array = np.array(df["week"])

In [13]:
# Dimensions to use matrix

len(week_array)
size = round(len(week_array)/ 2)

In [56]:
# Create matrix
week_matrix = week_array.reshape(size, 2)
test_array = np.array([2,3])

In [57]:
np.dot(week_matrix, test_array)

array([42, 31, 15, ..., 50, 57, 41])

In [71]:
test_array.reshape(-1, 1)

array([[2],
       [3]])

In [72]:
np.zeros([4, 3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])